name: MkDocs Deploy

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - mkdocs.yml
      - docs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Git settings
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages

      - name: Install MkDocs
        run: |
          python3 -m pip install setuptools
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Site deploy
        run: python3 -m mkdocs gh-deploy
